FROM ubuntu

RUN apt-get update -y
RUN apt-get install -y git

# sshキーの追加
ADD .ssh /root/.ssh
RUN chmod 600 /root/.ssh/*

WORKDIR /usr/local/Lingam-1/
RUN git clone git@github.com:tcu-seki-lab/lingam-1.git

